class WindowStyler:
    classic={'bar':
             {'bg':'gray',
             'fill':'black',
             'font':'TkTextFont',
             'relief':'groove',
              'image':''
             },
             'buttons':
             (
              ('kill',
               {'style':(
                 {'shape':'oval','fill':'#ca0000','outline':'black','text':''},
                 {'shape':'oval','fill':'#aa0000','outline':'gray55','text':''},
                 {'shape':'oval','fill':'#dda0a0','outline':'gray55'}
                 )}),
              ('max',
               {'style':(
                 {'shape':'oval','fill':'#00ca00','outline':'black','text':''},
                 {'shape':'oval','fill':'#00aa00','outline':'gray55','text':''},
                 {'shape':'oval','fill':'#a0dda0','outline':'gray55'}
                 )}),
              ('min',{'style':(
                 {'shape':'oval','fill':'#ddca00','outline':'black','text':''},
                 {'shape':'oval','fill':'#aaaa00','outline':'gray55','text':''},
                 {'shape':'oval','fill':'#ddddaa','outline':'gray55'}
                 )})
              ),
             'resizers':
             {'size':5,
              'bg':'gray85',
              'activebg':'gray',
              'activebd':'flat',
              'activewidth':5
##              'activebd':
              }
             }
    mac={'bar':
             {#'bg':'gray',
             'fill':'black',
             #'font':'TkTextFont',
             #'relief':'raised',
              'image':('mac','bar')
             },
             'buttons':
             (('kill',{'style':(('mac','close'),('mac','close'),('mac','red'))}),
              ('max',{'style':(('mac','max'),('mac','max'),('mac','green'))}),
              ('min',{'style':(('mac','min'),('mac','min'),('mac','yellow'))})
              ),
             'resizers':
             {'size':2,
              'activebg':'white',
              'activebd':'flat',
              }
             }
    retro={'bar':
             {'bg':'black',
             'fill':'green',
             'font':'TkFixedFont',
             'relief':'flat',
              'image':''
             },
             'buttons':
             (('kill',{'style':(('flat','close'),('flat','close'),('flat','')),
                       'tint':(255,0,0)}),
              ('max',{'style':(('flat','max'),('flat','max'),('flat','')),
                       'tint':(0,255,0)}),
              ('min',{'style':(('flat','min'),('flat','min'),('flat','')),
                       'tint':(255,255,0)})
              ),
               'resizers':
             {'size':5,
              'bg':'black',
              'activebg':'black',
              'activebd':'groove',
              'activewidth':5
              }
             }
    windows={'bar':
             {#'bg':'gray',
             'fill':'white',
             #'font':'TkTextFont',
             #'relief':'raised',
              'image':('windows','bar'),
             'pad':3,
             'button_spacing':1,
             'button_positioning':'right',
             'button_width':30,
             'height':32
             },
             'buttons':
             (('kill',{'style':(('windows','close'),('windows','close'),('windows','close'))}),
              ('max',{'style':(('windows','max'),('windows','max'),('windows','max'))}),
              ('min',{'style':(('windows','min'),('windows','min'),('windows','min'))})
              ),
              'resizers':
             {'size':5,
              'bg':'blue3',
              'activebg':'blue3',
              'activebd':'flat',
              'activewidth':5
              }
             }
             
    styles={'classic':classic,
            'mac':mac,
            'windows':windows,
            'retro':retro}
    def __init__(self,**new_styles):
        self.new_styles=new_styles
    def apply(self,window,style_name):
        try:
            s=self.new_styles[style_name]
        except KeyError:
            s=self.styles[style_name]
        window.bar_config(**s['bar'])
        for k,d in s['buttons']:
            window.button_config(k,**d)
        window.resizer_config(**s['resizers'])
